version: '3.8'

x-dev:
  &proxy_conf
  http_proxy: "${HTTP_PROXY}"
  https_proxy: "${HTTPS_PROXY}"

services:
  ui:
    container_name: ${APP_NAME}
    working_dir: /app
    image: node:14
    restart: on-failure
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3008:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
      << : *proxy_conf
    env_file:
      - .env
    command: tail -f /dev/null