# Generated by Django 3.2.9 on 2023-03-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_init'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.ManyToManyField(through='accounts.CustomUserRole', to='accounts.RoleModel'),
        ),
    ]
