# Generated by Django 3.2.9 on 2023-05-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0001_housekeeping'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='active',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='playermodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
