# Generated by Django 3.2.9 on 2023-04-26 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('housekeeping', '0001_housekeeping'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamemodel',
            name='players',
            field=models.ManyToManyField(through='game.PlayerGameModel', to='housekeeping.PlayerModel'),
        ),
        migrations.AlterField(
            model_name='playergamemodel',
            name='player',
            field=models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.DO_NOTHING, to='housekeeping.playermodel'),
        ),
        migrations.DeleteModel(
            name='PlayerModel',
        ),
    ]
